name: docker-react-app

on: 
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: docker build -t ikeshegs/docker-react -f Dockerfile.dev .

      - name: Run test
        run: npm test
